name:                uzi
language:            GHC2021
version:             0.2.1.0
github:              "githubuser/uzi"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/uzi#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- bytestring
- network
- aeson
- effectful
- effectful-core
- websockets
- wuss
- unliftio
- safe-exceptions
- lens 
- scientific
- string-conversions
- req
- either
- interpolate
- data-default
- parsec
- rio-log-effectful
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - NoImplicitPrelude

executables:
  uzi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uzi

tests:
  uzi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uzi
    - hspec
